### PR TITLE
Profile and images

### PR DESCRIPTION
**Pull request by Ochuwa-sophie**
I have added my profile and images

### CODE REVIEW

**Review by Layla-P — COMMENTED** [review]
Hey Sophie - I need you to make a few changes.

The tags are a little different now you can see a lit of them here: https://github.com/Layla-P/WomenOfDotNet/blob/main/content/profiles/_index.md

Also from Line 11 should be about you!  See my updated version here:
https://github.com/Layla-P/WomenOfDotNet/blob/main/content/profiles/layla-porter.md

**Comment by Layla-P** [comment]
Also, could you run the images through a tool such as https://tinypng.com/ to make them smaller?

**Review by Layla-P — APPROVED** [review]
Thanks for the updates!

**Comment by Ochuwa-sophie** [comment]
Thanks a bunch!

**Pull request merged**
